### ISSUE TITLE
invalid literal

### ISSUE THREAD

**Issue by reagle** [dooblem/bsync#29] opened 2016-05-27 20:55 UTC
Was testing the most recent version and got the following error:

```
Traceback (most recent call last):
  File "/home/reagle/bin/bsync", line 866, in <module>
    show_conflict(f1, f2, path)
  File "/home/reagle/bin/bsync", line 479, in show_conflict
    p1 = getfilemode(f1.type, f1.perms)+" "+f1.size+"B ("+getdatestr(f1)+")"
  File "/home/reagle/bin/bsync", line 469, in getfilemode
    return type + stat.filemode(int(perms, 8))[1:]
ValueError: invalid literal for int() with base 8: ''
```

**Comment by pdxvr** [comment] 2018-11-19 10:02
I get this all the time too.  I haven't figured it out yet, but it would be nice to.  I usually just delete my snapshots but that's a little risky

**Comment by pdxvr** [comment] 2018-12-07 05:07
I've had to stop using this as I started getting this all of the time.  I don't think it's a hard fix, but I don't know Python.  I understand what the error is and what it's doing, I just don't have the Python to fix it myself.

**Comment by dooblem** [comment] 2019-03-04 21:43
Hello @reagle @pdxvr 

Can you help me to reproduce? I not too confidential you may send me the .bsync-snap files.

On what filesystems are the files?

**Comment by reagle** [comment] 2019-03-04 22:43
I haven't used bsync since 2016 when I reported this.

**Comment by pdxvr** [comment] 2019-03-05 00:10
I stopped using this after my last post, however I'm willing to give it another run if you have the patience to wait until I'm able to reproduce the error.

**Comment by dooblem** [comment] 2019-03-05 08:37
Thanks @pdxvr . would be great. You may take your time as I did ;)

**Comment by dooblem** [comment] 2019-03-05 22:24
This is probably because you have a filesystem on fat.
Check #38 . at least now it should not crash.
I'm closing this in favor of #38

**Closed by dooblem** 2019-03-05 22:24 UTC

**Comment by pdxvr** [comment] 2019-03-06 11:17
I just ran the older version and got this error, installed the newest version and it worked.  Thanks!
